repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: check-merge-conflict

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: '8b76f04e7e5a9cd259e9d1db7799599355f97cdf'  # frozen: v0.8.2
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
    types_or: [python, pyi, jupyter]
